// ServicoConta.idl
interface ServicoConta {
    readonly attribute string nomeServico;
    readonly attribute string versaoServico;
    
    // Operações de consulta
    Conta obterInformacoesConta(in string numeroConta) 
        raises (ContaNaoEncontrada, ServicoIndisponivel);
    
    double consultarSaldo(in string numeroConta) 
        raises (ContaNaoEncontrada, ServicoIndisponivel);
    
    // Operações de atualização
    boolean atualizarConta(in Conta dadosConta) 
        raises (DadosInvalidos, ServicoIndisponivel);
    
    boolean alterarStatusConta(in string numeroConta, in string novoStatus)
        raises (ContaNaoEncontrada, StatusInvalido, ServicoIndisponivel);
    
    // Histórico e relatórios
    Transacao[] obterHistoricoTransacoes(
        in string numeroConta, 
        in data dataInicio, 
        in data dataFim
    ) raises (ContaNaoEncontrada, PeriodoInvalido, ServicoIndisponivel);
    
    Conta[] encontrarContasPorCliente(in string nomeCliente)
        raises (ServicoIndisponivel);
    
    // Status do serviço
    string obterStatusServico();
    string obterEstatisticasServico();
};